### ISSUE TITLE
cli create-test ->FileNotFoundException (II)

### ISSUE THREAD

**Issue by s-berg** [rockitconsulting/test.rockitizer#41]
depends on Issue #40 

rockitizer version: 1.0.5.2
CLI version: 1.0
java: 1.8.0_171
environment: Windows 10
after the user (me) input the command
cli create-test Xml2XmlMq2MqTest
the program throws an error: "FileNotFoundException .................. Xml2XmlMq2MqTest.java"
see screenshot attached:

![image](https://user-images.githubusercontent.com/62023045/76964216-a833e800-6922-11ea-8913-2e5208d2329f.png)

Possible solution

1. create folder:
    src\test\java

**Comment by rockitromansokunov** [comment]
This problem was caused by the absense of the Maven project layout. To solve this problem:

Please execute a Maven goal that will create the basic Maven project layout, e.g. mvn archetype:generate -DgroupId=com.group.id -DartifactId=java-project -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false

This will create /src/main/java/ and /src/test/java/ , which is the basic Maven project layout.
