### ISSUE TITLE
Question about Message Broker Unit testing

### ISSUE THREAD

**Issue by manoger** [rockitconsulting/test.rockitizer#45]
Hello. 👋
Is possible in this project to test inputs and outputs messages in between ACE nodes?
Callable Java functions by ESQL is possible to test as well?

Thanks in advance.

**Comment by MPA-rockIT** [comment]
Hallo there and thank you for the inquiry,

yes, you can test input and output messages in between ACE nodes.

For example you could implement one or more message flows that contain MQ Nodes as input and output points.
Creating and executing a test for the specific constellation in "record" mode, records the expected input and output message.
Executing the same test in "replay" mode will assert the results against the recorded (expected) input/output message.

Regarding the callable Java functions: 
from a strictly technical point of view that might be possible since **test.rockitizer** utilises JUnit. 
Conceptually such tests are really out of the scope of the **test.rockitizer** as the framework is oriented towards black box testing on the integration level. 

Instead you should provide your own Unit Tests in order to test the Java functions before moving to blackbox testing of the integration interface from which the ESQL/Java code is executed.

Best Regards
rockit.consulting Team

**Comment by manoger** [comment]
Thanks for the answers.
Now, I have got questions more.
Every ".bar" that I deploy in a production server, for example, should be attached to a ".jar"?
Do my tests become coupled with my projects?

**Comment by yefymdmukh** [comment]
No. Testsuite is externalized decoupled vehicle. You test your integration infrastructure of any complexity from outside. But in order to test the correctness of the logic you need to have access to relevant outputs (files, messages, http-repies, etc.)
